domain/urls.py
from django.conf.urls import url
from domain.views import SiteList,CreateSite,WebsiteDetailView
from domain import views

from rest_framework.urlpatterns import format_suffix_patterns



urlpatterns = [
    #Menu Items
    url(r'^$', views.Landing ,name='Landing'),
    url(r'^list$', SiteList.as_view(),name='site_list'),
    url(r'^create$', CreateSite.as_view(),name='create_site'),
    
    #Detail items
    url(r'^detail/(?P<pk>[-\w]+)/$', WebsiteDetailView.as_view(), name='domain-detail'),
    
    #Ajax Items
    
    url(r'^get_expiry_date$', views.get_expiry_date ,name='get_expiry_date'),
    url(r'^(?i)delete_domain/(?P<Record_id>[\w\d\ \-]+)$', views.delete_domain,name='delete_domain'),
    #API Views
    url(r'^api/$', views.Website_List.as_view()),
    url(r'^(?i)api/(?P<pk>[\w\d\ \-]+)$', views.WebsiteDetail.as_view()),
    
    ]
urlpatterns = format_suffix_patterns(urlpatterns)
'''
 

'''

domain/models.py
from __future__ import unicode_literals

from django.db import models

from django.conf import settings
from django.core.urlresolvers import reverse
from auditable.models import Auditable
from simple_history.models import HistoricalRecords

class Contact_information(Auditable):
    def __str__(self):
        return self.Contact_Name
    Contact_Name = models.CharField(max_length=100)
    Email = models.EmailField(max_length=100)
    Alerts_Enabled = models.BooleanField(default=False)

class CMS_info(models.Model):
    CMS = models.CharField(max_length=100,blank=True,null=True)
    def __str__(self):
        return self.CMS

class OS_Platform(models.Model):
    OS = models.CharField(max_length=100,blank=True,null=True)
    def __str__(self):
        return self.OS

class Department(models.Model):
    Department = models.CharField(max_length=100,blank=True,null=True)
    Contact_Person = models.CharField(max_length=100,blank=True,null=True)
    Contact_Person_Email = models.EmailField(max_length=100,blank=True,null=True)
    Contact_Number = models.CharField(max_length=100,blank=True,null=True)
    def __str__(self):
        return self.Department
    
HT_choices = (
              ('Shared','Shared'),
              ('Dedicated','Dedicated')
              )
   
class Website(Auditable):
    def __str__(self):
        return self.domain_name
    domain_name = models.CharField(max_length=100,unique=True)
    domain_provider = models.CharField(max_length=100)
    expiry_date = models.DateField(blank=True,null=True)
    Hosting_server = models.CharField(max_length=100,blank=True,null=True)
    Hosting_Type = models.CharField(max_length=20,choices=HT_choices,blank=True,null=True)
    hosting_provider = models.CharField(max_length=100,blank=True,null=True)
    auto_renewal = models.BooleanField(default=False)
    https_Enabled = models.BooleanField(default=False)
    Contacts = models.ManyToManyField(Contact_information,related_name='Websites',blank=True,)    
    CMS = models.ForeignKey(CMS_info)
    OS_Platform = models.ForeignKey(OS_Platform)
    comments = models.TextField(blank=True,null=True)
    history = HistoricalRecords()
    Developer = models.CharField(max_length=100,blank=True,null=True)
    Developer_Email = models.EmailField(max_length=100,blank=True,null=True)
    Developer_Contact_number = models.CharField(max_length=100,blank=True,null=True)
    Business_Department = models.ForeignKey(Department,related_name='department')
    CMS_Username = models.CharField(max_length=100,blank=True,null=True)
    CMS_Password = models.CharField(max_length=100,blank=True,null=True)
    Hosting_or_Cpanel_Username = models.CharField(max_length=100,blank=True,null=True)
    Hosting_or_Cpanel_Password = models.CharField(max_length=100,blank=True,null=True)

    class Meta:
        ordering = ["-domain_name"]
    
    def get_absolute_url(self):
        return reverse("site_list")

class DNS_Info(Auditable):
    def __str__(self):
        return self.domain_name.domain_name
    domain_name = models.ForeignKey(Website,on_delete=models.CASCADE,related_name='%(class)s_DNS_Info')
    A_Record = models.CharField(max_length=100,blank=True,null=True)
    CName_Record = models.CharField(max_length=100,blank=True,null=True)
    MX_Record = models.CharField(max_length=100,blank=True,null=True)
    history = HistoricalRecords()


   
class SSL_Information(models.Model):
    def __str__(self):
        return self.domain_name.domain_name
    domain_name = models.ForeignKey(Website,on_delete=models.CASCADE,related_name='SSL_Info')
    SSL_Presence = models.BooleanField(default=False)
    SSL_Expiry = models.DateField(blank=True,null=True)
    SSL_Provider = models.CharField(max_length=100,blank=True,null=True)

domain/forms.py
from django import forms
from domain.models import Website

class Future_DateWidget(forms.DateInput):
    def __init__(self, attrs=None, format=None):
        final_attrs = {'class': 'fut_DateField', 'size': '10'}
        if attrs is not None:
            final_attrs.update(attrs)
        super(Future_DateWidget, self).__init__(attrs=final_attrs, format=format)





class SiteForm(forms.ModelForm):
    class Meta:
        model=Website
        exclude = ['created_by','modified_by']
        widgets = {
            'domain_name': forms.TextInput(attrs={'required': True}),
            'domain_provider' : forms.TextInput(attrs={'required': True}),
            'expiry_date' : Future_DateWidget(),
            'Contacts' : forms.SelectMultiple(attrs={'class': 'form-control'})
        }
    MX_Records  = forms.CharField(required=False,widget=forms.TextInput())
    A_Record    = forms.CharField(required=False,widget=forms.TextInput())
    field_order = ['domain_name',
                                'expiry_date',
                                'auto_renewal',
                                'A_Record',
                                'MX_Records',
                                'Hosting_server',
                                'hosting_provider',
                                'domain_provider',
                                'comments',
                               ]  
    



domain/templates/domain/Copy of CreateSite.html
{% extends "unify/__form_skeleton.html" %}

{% load form_custom %}
{% load i18n %}

{% block Page_Theme %}purple.css{% endblock Page_Theme %}



{% block Style_sheets %}
	<link rel="stylesheet" href="/static/assets_u/plugins/animate.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/line-icons/line-icons.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/font-awesome/css/font-awesome.min.css">

	
	<link rel="stylesheet" href="/static/assets_u/plugins/sky-forms-pro/skyforms/css/sky-forms.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/line-icons/line-icons.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/scrollbar/css/jquery.mCustomScrollbar.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/owl-carousel/owl-carousel/owl.carousel.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/fancybox/source/jquery.fancybox.css">
	<!--[if lt IE 9]><link rel="stylesheet" href="assets/plugins/sky-forms-pro/skyforms/css/sky-forms-ie8.css"><![endif]-->

<style>





</style>

{% endblock Style_sheets %}


{% block Java_Scripts %}
	<script type="text/javascript" src="/static/assets_u/plugins/back-to-top.js"></script>
	<script type="text/javascript" src="/static/assets_u/plugins/smoothScroll.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.maskedinput.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery-ui.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.validate.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.form.min.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/masking.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/app.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/style-switcher.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/masking.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/datepicker.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/validation.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/style-switcher.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/style-switcher.js"></script>

	

	
	<script type="text/javascript">
		jQuery(document).ready(function() {
			App.init();
			Masking.initMasking();
			Datepicker.initDatepicker();
			Validation.initValidation();
			StyleSwitcher.initStyleSwitcher();
			App.initSidebarMenuDropdown();
			StyleSwitcher.initStyleSwitcher();

			
			$("#sky-form1").validate();
			
			$(".vDateField").datepicker({
					dateFormat : 'mm/dd/yy',
		            changeMonth : true,
		            changeYear : true,
		            yearRange: '-100y:c+nn',
		            maxDate: '-1d'
			});
			


		});
	</script>
	
{% endblock Java_Scripts %}

{% block Side_Bar %}
{% endblock Side_Bar %}


{% block Form %}
						


					{% if Notify %}
						
						<div class="tab-pane fade in" id="alert-2">
								<div class="margin-bottom-15"></div>
								<div class="alert alert-{{Notify.level}} fade in alert-dismissable">
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
									<i class="rounded-x fa fa-check"></i>
									<strong>{{Notify.level}}</strong> {{ Notify.Message}}
									{{forms.errors }}
								</div>
						</div>
					{% else %}
											
						<div id="alert-2"></div>
						
					{% endif %}
					
										<div class="margin-bottom-40"></div>

					<!-- Order Form -->
					{{form.errors}}
					<form action="" method="post" id="sky-form3" class="sky-form">
					{% csrf_token %} 
						<header>{{ Form_Title }} </header>
						<fieldset>
							
							<div class="row">
								{% for ind_form in form %}
								
								{% if ind_form|fieldtype == 'Textarea' %}
									<section class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
								{% else %}
									<section class="col col-lg-6 col-md-12 col-sm-10 col-xs-10">
								{% endif %}
									<div class="row">
										{% if ind_form|fieldtype == 'Textarea' %}	
											<label for="{{ind_form.id_for_label}}" class="label col col-2">{{ind_form.label}}</label>
										{% else %}
											<label for="{{ind_form.id_for_label}}" class="label col col-4">{{ind_form.label}}</label>
										{% endif %}
										<div class="col col-8">
											<label class="{{ind_form|field_label}}">
												{{ind_form}} 
											</label>
										</div>
									</div>
								</section>
								{% endfor %}
							</div>

						</fieldset>
						<footer>
							<button type="submit" class="btn-u">Submit</button>
							<div class="progress"></div>
						</footer>
						<div class="message">
							<i class="rounded-x fa fa-check"></i>
							<p>Thanks for your order!<br>We'll contact you very soon.</p>
						</div>
					</form>
					<!-- End Order Form -->
						

{% endblock Form %}

domain/templates/domain/Copy of generic_list.html
{% extends "unify/__table_view.html" %}
{% load i18n %}
{% load form_custom %}
{% block Page_Theme %}purple.css{% endblock Page_Theme %}
{% block Style_sheets %}
{% endblock Style_sheets %}
{% block Form %}
					<div id="alert-2"></div>
					<br><br>

					<div class="panel panel-grey margin-bottom-40">
						<div class="panel-heading">
							<h3 class="panel-title"><i class="fa fa-globe"></i>{{ Title }} </h3>
						</div>
						<div class="panel-body">
							    <table id='Table_list' class="table table-bordered">
								<thead>
									<tr>
										{% for field in Columns %}
											<th>{{field}}</th>
										{% endfor %}
									</tr>
								</thead>
								<tbody>
							
								{% for query in query_list %}
									<tr>
										{% for field in Columns %}
											<td>{{ query|get_value:field }}</td>
										{% endfor %}
										</td>						
									</tr>
								{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
					<!--End Table Bordered-->

					<div class="margin-bottom-60"></div>						

{% endblock Form %}

domain/templates/domain/CreateSite.html
{% extends "unify/__form_skeleton.html" %}
{% load staticfiles %}
{% load form_custom %}
{% load i18n %}

{% block Page_Theme %}purple.css{% endblock Page_Theme %}



{% block Style_sheets %}
	<link rel="stylesheet" href="/static/assets_u/plugins/animate.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/line-icons/line-icons.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/font-awesome/css/font-awesome.min.css">

	
	<link rel="stylesheet" href="/static/assets_u/plugins/sky-forms-pro/skyforms/css/sky-forms.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/line-icons/line-icons.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/scrollbar/css/jquery.mCustomScrollbar.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/owl-carousel/owl-carousel/owl.carousel.css">
	<link rel="stylesheet" href="/static/assets_u/plugins/fancybox/source/jquery.fancybox.css">
	<!--[if lt IE 9]><link rel="stylesheet" href="assets/plugins/sky-forms-pro/skyforms/css/sky-forms-ie8.css"><![endif]-->

<style>


label.required {
   font: italic 20px Georgia;

}

.required:after { content:"  *"; }


</style>

{% endblock Style_sheets %}


{% block Java_Scripts %}
	<script type="text/javascript" src="/static/assets_u/plugins/back-to-top.js"></script>
	<script type="text/javascript" src="/static/assets_u/plugins/smoothScroll.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.maskedinput.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery-ui.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.validate.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.form.min.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/masking.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/app.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/style-switcher.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/masking.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/datepicker.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/validation.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/style-switcher.js"></script>
	<script type="text/javascript" src="/static/assets_u/js/plugins/style-switcher.js"></script>
	<script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>

	

	
	<script type="text/javascript">
		jQuery(document).ready(function() {
			App.init();
			Masking.initMasking();
			Datepicker.initDatepicker();
			Validation.initValidation();
			StyleSwitcher.initStyleSwitcher();
			App.initSidebarMenuDropdown();
			StyleSwitcher.initStyleSwitcher();

			
			$("#sky-form3").validate();
			
			$(".vDateField").datepicker({
				dateFormat : 'mm/dd/yy',
	            changeMonth : true,
	            changeYear : true,
	            yearRange: '-100y:c+nn',
	            maxDate: '-1d'
		});
		
		
			$(".fut_DateField").datepicker({
			dateFormat : 'mm/dd/yy',
            changeMonth : true,
            changeYear : true,
            yearRange: '-100y:c+nn',
			});
			
			$("#id_domain_name").change(function(){
				
				
				domain_name = $("#id_domain_name").val()
			    ajaxPost('/domain/get_expiry_date', {'site_name': domain_name}, function(content){
			        //onSuccess
			        //alert(JSON.stringify(content))
			        var obj = JSON.stringify(content);
			        //alert(obj);
			        var json_obj = JSON.parse(obj);
			        //alert(loadPath.exp_date);
			        $("#id_expiry_date").val(json_obj.exp_date);
			        $("#id_domain_provider").val(json_obj.registrar);
			        $("#id_A_Record").val(json_obj.ip_addr);
			        $("#id_Hosting_server").val(json_obj.hosted_server);
			        $("#id_MX_Records").val(json_obj.mx);
			        
			        
			        
			    });
				
				
			});
			
			$(".add_new_value").click(function(){
				
				
				
			});
			
		});
	</script>
{% endblock Java_Scripts %}

{% block Side_Bar %}
{% endblock Side_Bar %}


{% block Form %}
						


					{% if Notify %}
						
						<div class="tab-pane fade in" id="alert-2">
								<div class="margin-bottom-15"></div>
								<div class="alert alert-{{Notify.level}} fade in alert-dismissable">
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
									<i class="rounded-x fa fa-check"></i>
									<strong>{{Notify.level}}</strong> {{ Notify.Message}}
									{{forms.errors }}
								</div>
						</div>
					{% elif form.errors %}
						<div class="tab-pane fade in" id="alert-2">
							<div class="margin-bottom-15"></div>
								<div class="alert alert-warning fade in alert-dismissable">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<i class="rounded-x fa fa-exclamation-triangle"></i>
								<strong>Error!!<br></strong> {{ form.errors }}
								</div>	
								
						</div>
					{% else	%} 			
						<div id="alert-2"></div>
						
					{% endif %}

										<div class="margin-bottom-40"></div>

					<!-- Order Form -->

					<form action="" method="post" id="sky-form3" class="sky-form">
					{% csrf_token %} 
						<header>{{ Form_Title }} </header>
						
						<fieldset>
							
							<div class="row">
								{% for ind_form in form %}
								
								{% if ind_form|fieldtype == 'Textarea' %}
									<section class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
								{% else %}
									<section class="col col-lg-7 col-md-12 col-sm-10 col-xs-10">
								{% endif %}
									<div class="row">
										{% if ind_form|fieldtype == 'Textarea' %}	
											<label for="{{ind_form.id_for_label}}" class="label col col-2">{{ind_form.label}}</label>
										{% else %}
											<label for="{{ind_form.id_for_label}}" class="label col col-4 {{ ind_form.field.widget.is_required |yesno:'required,'}}">{{ind_form.label}}</label>
											
										{% endif %}
										<div class="col col-7">
											<label class="{{ind_form|field_label}}">
												{{ind_form}} 
											</label>
										</div>
										{% if ind_form|fieldtype == 'SelectMultiple' %}
												<div class="col-sm-1">
													<button type="button" id="{{ind_form.id_for_label}}_btn" class="btn-u btn-u-sea add_new_value"><i class="fa fa-plus"></i></button>
												</div>
										{% endif %}
										
									</div>
								</section>
								{% endfor %}
							</div>

						</fieldset>
						<footer>
							<button type="submit" class="btn-u">Submit</button>
							<div class="progress"></div>
						</footer>
						<div class="message">
							<i class="rounded-x fa fa-check"></i>
							<p>Thanks for your order!<br>We'll contact you very soon.</p>
						</div>
					</form>
					<!-- End Order Form -->
						

{% endblock Form %}

domain/templates/domain/Landing.html
{% extends "unify/__table_view.html" %}

{% load form_custom %}
{% load i18n %}

{% block Style_sheets %} .
	
{% endblock Style_sheets %}


{% block Java_Scripts %}
<script type="text/javascript" src="/static/assets_u/plugins/counter/waypoints.min.js"></script>
<script type="text/javascript" src="/static/assets_u/plugins/counter/jquery.counterup.min.js"></script>
<script type="text/javascript" src="/static/assets_u/js/app.js"></script>

<script type="text/javascript">
jQuery(document).ready(function() {
			App.init();
			App.initCounter();
		});
</script>
{% endblock %}


{% block Content %}

<div class="row">

<div class="col-xs-12 col-lg-12 col-md-12 col-sm-12">
{% block Form %}

						<!-- Counters -->
						<div class="main-counters margin-bottom-30">
							<div class="headline"><h2>Websites Information</h2></div>
							<div class="row margin-bottom-40">
								<div class="counters col-md-3 col-sm-3">
									<span class="counter">{{ Pay_load.Total_websites }}</span>
									<h4>Websites</h4>
								</div>
								<div class="counters col-md-3 col-sm-3">
									<span class="counter">{{ Pay_load.SSL_Certificates }}</span>
									<h4>SSL Certificates</h4>
								</div>
								<div class="counters col-md-3 col-sm-3">
									<span class="counter">0</span>
									<h4>Parked Domains</h4>
								</div>
							</div>
						

							<div class="headline"><h2>DataBases Information</h2></div>

							<div class="row margin-bottom-40">
								<div class="counters col-md-3 col-sm-3">
									<span class="counter">{{ Pay_load.Total_databases }}</span>
									<h4>Databases</h4>
								</div>

							</div>
							

							
							
							<!-- 
							<div class="margin-bottom-50"><hr></div>

							<div class="row">
								<div class="counters col-md-3 col-sm-3">
									<span class="counter-icon"><i class="fa fa-gift rounded"></i></span>
									<span class="counter">3254</span>
								</div>
								<div class="counters col-md-3 col-sm-3">
									<span class="counter-icon"><i class="fa fa-coffee rounded"></i></span>
									<span class="counter">7068</span>
								</div>
								<div class="counters col-md-3 col-sm-3">
									<span class="counter-icon"><i class="fa fa-thumbs-up rounded"></i></span>
									<span class="counter">5389</span>
								</div>
								<div class="counters col-md-3 col-sm-3">
									<span class="counter-icon"><i class="fa fa-comments rounded"></i></span>
									<span class="counter">9172</span>
								</div>
							</div>
							 -->
						</div>
						<!-- End Counters -->

{% endblock Form %}
</div>

</div>
{% endblock Content %}

domain/templates/domain/generic_list.html
{% extends "unify/__table_view.html" %}
{% load i18n %}
{% load form_custom %}
{% block Page_Theme %}purple.css{% endblock Page_Theme %}


{% block Style_sheets %}
	
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
	<!--[if lt IE 9]><link rel="stylesheet" href="assets/plugins/sky-forms-pro/skyforms/css/sky-forms-ie8.css"><![endif]-->
	

{% endblock Style_sheets %}

{% block Form %}
					<div id="alert-2"></div>
					<br><br>

					<div class="panel panel-grey margin-bottom-40">
						<div class="panel-heading">
							<h3 class="panel-title"><i class="fa fa-globe"></i>{{ Title }} </h3>
						</div>
						<div class="panel-body">
							    <table id='Table_list' class="table table-bordered">
								<thead>
									<tr>
										<th>Domain Name</th>
										{% for field in Columns %}
											<th>{{field}}</th>
										{% endfor %}
										<th>Status</th>	
									</tr>
								</thead>
								<tbody>
							
								{% for query in query_list %}
									<tr>
										<td><a href="/domain/detail/{{query.id}}">{{query.domain_name}}</a></td>
										{% for field in Columns %}
											<td>{{ query|get_value:field }}</td>
										{% endfor %}
										<td>
											<button class="btn btn-warning btn-xs more_button" value={{query.id}}><i class="fa fa-pencil"></i>More</button>
											<button class="btn btn-warning btn-xs edit_button" value={{query.id}}><i class="fa fa-pencil"></i>Edit</button>
											<button class="btn btn-danger btn-xs delete_button" value={{query.id}}><i class="fa fa-trash-o"></i></button>
										</td>						
									</tr>
								{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
					<!--End Table Bordered-->

					<div class="margin-bottom-60"></div>						

{% endblock Form %}

{% block Java_Scripts %}
	<script type="text/javascript" src="/static/assets_u/plugins/back-to-top.js"></script>
	<script type="text/javascript" src="/static/assets_u/plugins/smoothScroll.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.maskedinput.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery-ui.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.validate.min.js"></script>
	<script src="/static/assets_u/plugins/sky-forms-pro/skyforms/js/jquery.form.min.js"></script>
	<script src="http://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="/static/js/bootbox.min.js"></script>
	
	
	<script type="text/javascript">
		jQuery(document).ready(function() {
			
			//$('#Table_list').DataTable();
			
			var oTable = $('#Table_list').DataTable({
				"fnDrawCallback":function(oSettings){
					
					  $('.more_button').click(function() {
						    alert($(this).attr('value'));
						  });
						  
						  $('.edit_button').click(function() {
							  	var instance = $(this).attr('value');
							  	window.location.href = "/irm/edit_agency/"+instance
							  });
						  
						  $('.delete_button').click(function() {
		  				  	  	  agency_id = $(this).attr('value')							 
							      bootbox.confirm("Are you sure you want to delte domain with ID " + agency_id + " ?" , function(result) {
							    	  $.ajax('/domain/delete_domain/'+agency_id, { 
											type: 'POST',
											dataType : "html",	
											data :  { csrfmiddlewaretoken: '{{ csrf_token }}'}, 
																												
											success: 	function(get_record_html) {
												location.reload();															
												$('#alert-2').replaceWith(get_record_html)
												

												 },

											error : function(xhr,errmssg,transport_html) {
												console.log('Failure');
												console.log(transport_html);
												console.log(errmssg);
													}
												}); // end new Ajax.Request
								  
								     }); 
							  }); 
				}
				});

		});
	</script>
	
{% endblock Java_Scripts %}